
###############################################################################
#
# Inclusive Makefile for the orc-build module.
#
# Autogenerated 2016-02-01 22:49:43.472489
#
###############################################################################
orc-build_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

