sudo: required

language: c

git:
  submodules: false
  
services:
  - docker
  
before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq realpath
- sudo cp ~/OpenNetworkLinux/docker/tools/onlbuilder /usr/local/bin/onlbuilder

script:
- tools/autobuild/run.sh -b master
