
###############################################################################
#
# Inclusive Makefile for the platform_underscore module.
#
# Autogenerated 2015-12-23 23:45:56.754200
#
###############################################################################
platform_underscore_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(platform_underscore_BASEDIR)/module/make.mk
include $(platform_underscore_BASEDIR)/module/auto/make.mk
include $(platform_underscore_BASEDIR)/module/src/make.mk

