
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-qwave-hawk module.
#
# Autogenerated 2016-07-08 23:57:53.296989
#
###############################################################################
libonlp-x86-64-qwave-hawk_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

