
###############################################################################
#
# Inclusive Makefile for the x86_64_qwave_hawk module.
#
# Autogenerated 2016-07-09 00:09:28.836547
#
###############################################################################
x86_64_qwave_hawk_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

