
###############################################################################
#
# Inclusive Makefile for the libonlp-platform-dash module.
#
# Autogenerated 2016-09-22 17:01:39.748162
#
###############################################################################
libonlp-platform-dash_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

