###############################################################################
# Inclusive Makefile for the platform_undescore module.
#
# Autogenerated 2015-12-23 23:45:22.262891
#
###############################################################################
platform_underscore_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
