
###############################################################################
#
# Inclusive Makefile for the orc-build module.
#
# Autogenerated 2016-01-04 20:58:38.285525
#
###############################################################################
orc-build_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

